name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  CMAKE_VERSION: "4.2.3"

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CMake ${{ env.CMAKE_VERSION }}
        run: pip install cmake==${{ env.CMAKE_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14 pkg-config autoconf automake libtool make gcc

      - name: Configure
        env:
          CXX: g++-14
        run: cmake --preset linux-x86_64-release

      - name: Build
        run: cmake --build --preset linux-x86_64-release --parallel
